/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package View;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import java.awt.BorderLayout;
import java.awt.ComponentOrientation;
import java.awt.image.BufferedImage;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.jdesktop.swingx.JXDatePicker;
import org.jdesktop.swingx.JXFormattedTextField;
import org.jdesktop.swingx.JXList;
import outils.I18n;

/**
 *
 * @author Ould_Hamdi
 */
public class View extends javax.swing.JFrame {

    /** Creates new form View */
    public View() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genre = new javax.swing.ButtonGroup();
        modeStage = new javax.swing.ButtonGroup();
        gesta = new javax.swing.JPanel();
        espacePrincipale = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lFiltre = new javax.swing.JLabel();
        lSemestre2 = new javax.swing.JLabel();
        lSpecialite2 = new javax.swing.JLabel();
        listeSemestre = new javax.swing.JComboBox<>();
        listeSpecialite = new javax.swing.JComboBox<>();
        btnImprimDoc = new javax.swing.JButton();
        lMode2 = new javax.swing.JLabel();
        listeModeStage = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        rechercher = new javax.swing.JTextField();
        btnSupprimerStagiaire = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listeStagiaire = new org.jdesktop.swingx.JXList();
        document = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        photo = new javax.swing.JPanel();
        btnSupprimer = new javax.swing.JButton();
        btnChanger = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lAdresse = new javax.swing.JLabel();
        lInfoS = new javax.swing.JLabel();
        adresse = new javax.swing.JTextField();
        lPrenom = new javax.swing.JLabel();
        lDateLieu = new javax.swing.JLabel();
        lGenre = new javax.swing.JLabel();
        lTelephone = new javax.swing.JLabel();
        lEmail = new javax.swing.JLabel();
        lNom = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        numero = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        dateNaissance = new org.jdesktop.swingx.JXDatePicker();
        lieu = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        homme = new javax.swing.JRadioButton();
        femme = new javax.swing.JRadioButton();
        lInfoP = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        codeQr = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        btnVider = new javax.swing.JButton();
        btnEnregistrer = new javax.swing.JButton();
        btnMAJ = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        lGroupe = new javax.swing.JLabel();
        groupe = new javax.swing.JTextField();
        lMatricule = new javax.swing.JLabel();
        matricule = new javax.swing.JTextField();
        lSpecialite = new javax.swing.JLabel();
        specialite = new javax.swing.JTextField();
        lMode = new javax.swing.JLabel();
        semestre = new javax.swing.JTextField();
        lSemestre = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        residentiel = new javax.swing.JRadioButton();
        apprentissage = new javax.swing.JRadioButton();
        coursDeSoir = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fichier = new javax.swing.JMenu();
        tabExcel = new javax.swing.JMenuItem();
        ficExcel = new javax.swing.JMenuItem();
        langue = new javax.swing.JMenu();
        francais = new javax.swing.JMenuItem();
        arabe = new javax.swing.JMenuItem();
        aide = new javax.swing.JMenu();
        aPropos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        quitter = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gesta");

        gesta.setBackground(new java.awt.Color(255, 255, 255));
        gesta.setLayout(new java.awt.BorderLayout());

        espacePrincipale.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(245, 247, 250));

        lFiltre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lFiltre.setForeground(new java.awt.Color(31, 60, 136));
        lFiltre.setText("Filtrer par");

        lSemestre2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lSemestre2.setForeground(new java.awt.Color(31, 60, 136));
        lSemestre2.setText("Semestre:");

        lSpecialite2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lSpecialite2.setForeground(new java.awt.Color(31, 60, 136));
        lSpecialite2.setText("Specialite:");

        listeSemestre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        listeSpecialite.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        btnImprimDoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnImprimDoc.setText("Imprimer document");

        lMode2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lMode2.setForeground(new java.awt.Color(31, 60, 136));
        lMode2.setText("Mode Stage:");

        listeModeStage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listeModeStage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tout الكل", "residentiel", "apprentissage", "Cours de Soir" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lFiltre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lSemestre2)
                            .addComponent(lSpecialite2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(listeSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listeSpecialite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(lMode2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listeModeStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImprimDoc)))
                .addContainerGap(494, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lFiltre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lSemestre2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lSpecialite2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listeSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lMode2))
                            .addComponent(listeModeStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listeSpecialite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImprimDoc)
                .addContainerGap())
        );

        espacePrincipale.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 400));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(245, 247, 250));
        jPanel4.setPreferredSize(new java.awt.Dimension(250, 50));
        jPanel4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jPanel4AncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rechercher.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel4.add(rechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 170, 30));

        btnSupprimerStagiaire.setBackground(new java.awt.Color(198, 40, 40));
        btnSupprimerStagiaire.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSupprimerStagiaire.setForeground(new java.awt.Color(255, 255, 255));
        btnSupprimerStagiaire.setText("Supprimer");
        jPanel4.add(btnSupprimerStagiaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 30));

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(245, 247, 250));

        listeStagiaire.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listeStagiaire.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jScrollPane2.setViewportView(listeStagiaire);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        espacePrincipale.add(jPanel2, java.awt.BorderLayout.LINE_START);

        document.setBackground(new java.awt.Color(51, 0, 51));
        document.setForeground(new java.awt.Color(0, 0, 51));
        document.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(549, 350));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(63, 187, 192));
        jPanel6.setPreferredSize(new java.awt.Dimension(250, 250));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        photo.setBackground(new java.awt.Color(245, 247, 250));
        photo.setLayout(new javax.swing.BoxLayout(photo, javax.swing.BoxLayout.LINE_AXIS));
        jPanel6.add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 32, 210, 220));

        btnSupprimer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSupprimer.setText("Supprimer");
        jPanel6.add(btnSupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        btnChanger.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnChanger.setText("Changer");
        jPanel6.add(btnChanger, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jPanel5.add(jPanel6, java.awt.BorderLayout.LINE_START);

        jPanel7.setBackground(new java.awt.Color(63, 187, 192));
        jPanel7.setPreferredSize(new java.awt.Dimension(257, 100));

        lAdresse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lAdresse.setForeground(new java.awt.Color(31, 60, 136));
        lAdresse.setText("Adresse:");

        lInfoS.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lInfoS.setForeground(new java.awt.Color(31, 60, 136));
        lInfoS.setText("Informations Scolaire");

        adresse.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lPrenom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lPrenom.setForeground(new java.awt.Color(31, 60, 136));
        lPrenom.setText("Prenom:");

        lDateLieu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lDateLieu.setForeground(new java.awt.Color(31, 60, 136));
        lDateLieu.setText("Date-Lieu Naissance:");

        lGenre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lGenre.setForeground(new java.awt.Color(31, 60, 136));
        lGenre.setText("Genre:");

        lTelephone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lTelephone.setForeground(new java.awt.Color(31, 60, 136));
        lTelephone.setText("Telephone:");

        lEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lEmail.setForeground(new java.awt.Color(31, 60, 136));
        lEmail.setText("Email:");

        lNom.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lNom.setForeground(new java.awt.Color(31, 60, 136));
        lNom.setText("Nom:");

        nom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        prenom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        numero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel8.setBackground(new java.awt.Color(63, 187, 192));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(dateNaissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, -1));

        lieu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel8.add(lieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 130, -1));

        jPanel9.setBackground(new java.awt.Color(63, 187, 192));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        genre.add(homme);
        homme.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homme.setForeground(new java.awt.Color(31, 60, 136));
        homme.setText("Homme");
        homme.setActionCommand("homme");
        jPanel9.add(homme, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        genre.add(femme);
        femme.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        femme.setForeground(new java.awt.Color(31, 60, 136));
        femme.setText("Femme");
        femme.setActionCommand("femme");
        jPanel9.add(femme, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, -1));

        lInfoP.setBackground(new java.awt.Color(31, 60, 136));
        lInfoP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lInfoP.setForeground(new java.awt.Color(31, 60, 136));
        lInfoP.setText("Informations Personnel");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lInfoP))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lNom)
                .addGap(24, 24, 24)
                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(lPrenom)
                .addGap(19, 19, 19)
                .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lDateLieu)
                .addGap(23, 23, 23)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(lGenre)
                .addGap(24, 24, 24)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lTelephone)
                .addGap(25, 25, 25)
                .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(lInfoS))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lAdresse)
                    .addComponent(lEmail))
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(lInfoP)
                .addGap(5, 5, 5)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lNom)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lPrenom)
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lDateLieu)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lGenre)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTelephone)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lEmail))
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lAdresse)))
                .addGap(18, 18, 18)
                .addComponent(lInfoS))
        );

        jPanel5.add(jPanel7, java.awt.BorderLayout.CENTER);

        document.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel11.setBackground(new java.awt.Color(63, 187, 192));
        jPanel11.setPreferredSize(new java.awt.Dimension(200, 191));

        codeQr.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(codeQr, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(codeQr, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        document.add(jPanel11, java.awt.BorderLayout.LINE_END);

        jPanel12.setBackground(new java.awt.Color(63, 187, 192));
        jPanel12.setPreferredSize(new java.awt.Dimension(780, 50));

        btnVider.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVider.setText("Vider");

        btnEnregistrer.setBackground(new java.awt.Color(46, 125, 50));
        btnEnregistrer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEnregistrer.setForeground(new java.awt.Color(255, 255, 255));
        btnEnregistrer.setText("Enregistrer");

        btnMAJ.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMAJ.setText("Mettre a jour");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnVider)
                .addGap(50, 50, 50)
                .addComponent(btnEnregistrer)
                .addGap(57, 57, 57)
                .addComponent(btnMAJ)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVider)
                    .addComponent(btnEnregistrer)
                    .addComponent(btnMAJ))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        document.add(jPanel12, java.awt.BorderLayout.PAGE_END);

        jPanel13.setBackground(new java.awt.Color(63, 187, 192));
        jPanel13.setPreferredSize(new java.awt.Dimension(600, 191));

        lGroupe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lGroupe.setForeground(new java.awt.Color(31, 60, 136));
        lGroupe.setText("Groupe:");

        groupe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lMatricule.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lMatricule.setForeground(new java.awt.Color(31, 60, 136));
        lMatricule.setText("Matricule:");

        matricule.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lSpecialite.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lSpecialite.setForeground(new java.awt.Color(31, 60, 136));
        lSpecialite.setText("Specialite:");

        specialite.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lMode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lMode.setForeground(new java.awt.Color(31, 60, 136));
        lMode.setText("Mode  Stage:");

        semestre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lSemestre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lSemestre.setForeground(new java.awt.Color(31, 60, 136));
        lSemestre.setText("Semestre:");

        jPanel14.setBackground(new java.awt.Color(63, 187, 192));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modeStage.add(residentiel);
        residentiel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        residentiel.setForeground(new java.awt.Color(31, 60, 136));
        residentiel.setText("Residentiel");
        residentiel.setActionCommand("residentiel");
        jPanel14.add(residentiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        modeStage.add(apprentissage);
        apprentissage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        apprentissage.setForeground(new java.awt.Color(31, 60, 136));
        apprentissage.setText("Apprentssage");
        apprentissage.setActionCommand("apprentissage");
        jPanel14.add(apprentissage, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 140, -1));

        modeStage.add(coursDeSoir);
        coursDeSoir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        coursDeSoir.setForeground(new java.awt.Color(31, 60, 136));
        coursDeSoir.setText("Cours de Soir");
        coursDeSoir.setActionCommand("cours de Soir");
        jPanel14.add(coursDeSoir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lMatricule)
                .addGap(14, 14, 14)
                .addComponent(matricule, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lSpecialite)
                .addGap(13, 13, 13)
                .addComponent(specialite, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lSemestre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(semestre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lGroupe)
                .addGap(22, 22, 22)
                .addComponent(groupe, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lMode)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lMatricule)
                    .addComponent(matricule, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lSpecialite))
                    .addComponent(specialite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(semestre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lSemestre))
                    .addComponent(lGroupe)
                    .addComponent(groupe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lMode)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        document.add(jPanel13, java.awt.BorderLayout.CENTER);

        espacePrincipale.add(document, java.awt.BorderLayout.CENTER);

        gesta.add(espacePrincipale, java.awt.BorderLayout.CENTER);

        getContentPane().add(gesta, java.awt.BorderLayout.CENTER);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        fichier.setText("Fichier");

        tabExcel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tabExcel.setText("Exporter la liste en tableau Excel");
        fichier.add(tabExcel);

        ficExcel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ficExcel.setText("Importer une liste Excel");
        fichier.add(ficExcel);

        jMenuBar1.add(fichier);

        langue.setText("Langue");
        langue.setToolTipText("");

        francais.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        francais.setText("Francais");
        langue.add(francais);

        arabe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        arabe.setText("العربية");
        langue.add(arabe);

        jMenuBar1.add(langue);

        aide.setText("Aide");

        aPropos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aPropos.setText("A propos");
        aide.add(aPropos);
        aide.add(jSeparator1);

        quitter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        quitter.setText("Quitter");
        aide.add(quitter);

        jMenuBar1.add(aide);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel4AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4AncestorMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                View l=new View();
                l.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aPropos;
    private javax.swing.JTextField adresse;
    private javax.swing.JMenu aide;
    private javax.swing.JRadioButton apprentissage;
    private javax.swing.JMenuItem arabe;
    private javax.swing.JButton btnChanger;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JButton btnImprimDoc;
    private javax.swing.JButton btnMAJ;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnSupprimerStagiaire;
    private javax.swing.JButton btnVider;
    private javax.swing.JPanel codeQr;
    private javax.swing.JRadioButton coursDeSoir;
    private org.jdesktop.swingx.JXDatePicker dateNaissance;
    private javax.swing.JPanel document;
    private javax.swing.JTextField email;
    private javax.swing.JPanel espacePrincipale;
    private javax.swing.JRadioButton femme;
    private javax.swing.JMenuItem ficExcel;
    private javax.swing.JMenu fichier;
    private javax.swing.JMenuItem francais;
    private javax.swing.ButtonGroup genre;
    private javax.swing.JPanel gesta;
    private javax.swing.JTextField groupe;
    private javax.swing.JRadioButton homme;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lAdresse;
    private javax.swing.JLabel lDateLieu;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lFiltre;
    private javax.swing.JLabel lGenre;
    private javax.swing.JLabel lGroupe;
    private javax.swing.JLabel lInfoP;
    private javax.swing.JLabel lInfoS;
    private javax.swing.JLabel lMatricule;
    private javax.swing.JLabel lMode;
    private javax.swing.JLabel lMode2;
    private javax.swing.JLabel lNom;
    private javax.swing.JLabel lPrenom;
    private javax.swing.JLabel lSemestre;
    private javax.swing.JLabel lSemestre2;
    private javax.swing.JLabel lSpecialite;
    private javax.swing.JLabel lSpecialite2;
    private javax.swing.JLabel lTelephone;
    private javax.swing.JMenu langue;
    private javax.swing.JTextField lieu;
    private javax.swing.JComboBox<String> listeModeStage;
    private javax.swing.JComboBox<String> listeSemestre;
    private javax.swing.JComboBox<String> listeSpecialite;
    private org.jdesktop.swingx.JXList listeStagiaire;
    private javax.swing.JTextField matricule;
    private javax.swing.ButtonGroup modeStage;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField numero;
    private javax.swing.JPanel photo;
    private javax.swing.JTextField prenom;
    private javax.swing.JMenuItem quitter;
    private javax.swing.JTextField rechercher;
    private javax.swing.JRadioButton residentiel;
    private javax.swing.JTextField semestre;
    private javax.swing.JTextField specialite;
    private javax.swing.JMenuItem tabExcel;
    // End of variables declaration//GEN-END:variables
    public JTextField getAdresse() {
        return adresse;
    }





    public JButton getBtnChanger() {
        return btnChanger;
    }

    public JButton getBtnEnregistrer() {
        return btnEnregistrer;
    }


    public JButton getBtnImprimDoc() {
        return btnImprimDoc;
    }

    public JButton getBtnSupprimer() {
        return btnSupprimer;
    }

    public JButton getBtnVider() {
        return btnVider;
    }

    public JTextField getEmail() {
        return email;
    }

    public ButtonGroup getGenre() {
        return genre;
    }

    public JTextField getGroupe() {
        return groupe;
    }



    public JTextField getLieu() {
        return lieu;
    }

    public JXList getListeStagiaire() {
        return listeStagiaire;
    }

    public JTextField getMatricule() {
        return matricule;
    }

    public ButtonGroup getModeStage() {
        return modeStage;
    }


    public JTextField getNom() {
        return nom;
    }

    public JPanel getPhoto() {
        return photo;
    }

    public JTextField getPrenom() {
        return prenom;
    }

    public JTextField getRechercher() {
        return rechercher;
    }

    public JTextField getSemestre() {
        return semestre;
    }

    public JTextField getSpecialite() {
        return specialite;
    }

    public JTextField getTelephone() {
        return numero;
    }

    public void setPhoto(JPanel photo) {
        this.photo = photo;
    }

    public JPanel getCodeQr() {
        return codeQr;
    }

    public JXDatePicker getDateNaissance() {
        return dateNaissance;
    }
    DocumentListener laisserSauvegarder=new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
         laisserSauvegarder();}

        @Override
        public void removeUpdate(DocumentEvent e) {
         laisserSauvegarder();}

        @Override
        public void changedUpdate(DocumentEvent e) {
            laisserSauvegarder();
        }
    };
    private void laisserSauvegarder(){
        btnEnregistrer.setEnabled(
                !nom.getText().isEmpty() && !prenom.getText().isEmpty() && !lieu.getText().isEmpty() &&
                !matricule.getText().isEmpty() && !semestre.getText().isEmpty() && !specialite.getText().isEmpty() &&
                genre.getSelection()!=null && modeStage.getSelection()!=null&& dateNaissance.getDate()!=null
        );
        btnMAJ.setEnabled(
                !nom.getText().isEmpty() && !prenom.getText().isEmpty() && !lieu.getText().isEmpty() &&
                !matricule.getText().isEmpty() && !semestre.getText().isEmpty() && !specialite.getText().isEmpty() &&
                genre.getSelection()!=null && modeStage.getSelection()!=null&& dateNaissance.getDate()!=null
        );
        actualiserQr();
    }
    public void actualiserQr(){
        String text="""
                    %s%s
                    %s%s
                    %s %s - %s
                    %s%s
                    %s%s
                    %s%s
                    """.formatted(
                    lNom.getText(),nom.getText(),
                    lPrenom.getText(),prenom.getText(),
                    lDateLieu.getText(),
                    (dateNaissance.getDate()!=null)
                    ?new SimpleDateFormat("dd-MM-yyyy").format(dateNaissance.getDate())
                    :null,
                    lieu.getText(),
                    lSpecialite.getText(),specialite.getText(),
                    lSemestre.getText(),semestre.getText(),
                    lMatricule.getText(),matricule.getText()
                    );
        
        if(!text.isEmpty()){
            try{
                BufferedImage qr=genererQr(text);
                if(qr!=null){
                    JLabel image=new JLabel(new ImageIcon(qr));
                    codeQr.removeAll();
                    codeQr.add(image,BorderLayout.CENTER);
                    codeQr.revalidate();
                    codeQr.repaint();
                }
            }catch(Exception e){
                
            }
        }
    }
    public BufferedImage genererQr(String texte){
        QRCodeWriter qrW=new QRCodeWriter();
        try {
            Map<EncodeHintType,Object> encoderUTF8=new HashMap<>();
            encoderUTF8.put(EncodeHintType.CHARACTER_SET, "UTF-8");
            BitMatrix matrice=qrW.encode(texte, BarcodeFormat.QR_CODE, codeQr.getBounds().width, codeQr.getBounds().height,encoderUTF8);
            return MatrixToImageWriter.toBufferedImage(matrice);
        } catch (WriterException ex) {
            return null;
        }
        
    }
    public void ajouterDocumentListener(){
        nom.getDocument().addDocumentListener(laisserSauvegarder);
        prenom.getDocument().addDocumentListener(laisserSauvegarder);
        matricule.getDocument().addDocumentListener(laisserSauvegarder);
        semestre.getDocument().addDocumentListener(laisserSauvegarder);
        specialite.getDocument().addDocumentListener(laisserSauvegarder);
        groupe.getDocument().addDocumentListener(laisserSauvegarder);
        lieu.getDocument().addDocumentListener(laisserSauvegarder);
        homme.addActionListener(e->{
            laisserSauvegarder();
        });
        femme.addActionListener(e->{
            laisserSauvegarder();
        });
        residentiel.addActionListener(e->{
            laisserSauvegarder();
        });
        apprentissage.addActionListener(e->{
            laisserSauvegarder();
        });
        coursDeSoir.addActionListener(e->{
            laisserSauvegarder();
        });
        dateNaissance.addActionListener(e->{
            laisserSauvegarder();
    });
    }

    public JComboBox<String> getListeSemestre() {
        return listeSemestre;
    }

    public JComboBox<String> getListeSpecialite() {
        return listeSpecialite;
    }

    public JComboBox<String> getListeModeStage() {
        return listeModeStage;
    }
    
    public JButton getBtnMAJ() {
        return btnMAJ;
    }

    public JButton getBtnSupprimerStagiaire() {
        return btnSupprimerStagiaire;
    }

    public JPanel getDocument() {
        return document;
    }

    public JMenuItem getaPropos() {
        return aPropos;
    }

    

    public JMenuItem getQuitter() {
        return quitter;
    }

    public JMenuItem getArabe() {
        return arabe;
    }

    public JMenuItem getFrancais() {
        return francais;
    }

    public JMenuItem getTabExcel() {
        return tabExcel;
    }

    public JMenuItem getFicExcel() {
        return ficExcel;
    }
    
    public void appliquerLangue(){
        lSemestre.setText(I18n.texte("label.semestre"));
        lSemestre2.setText(I18n.texte("label.semestre"));
        lSpecialite.setText(I18n.texte("label.spec"));
        lSpecialite2.setText(I18n.texte("label.spec"));
        setTitle(I18n.texte("titre"));
        btnEnregistrer.setText(I18n.texte("button.enregistrer"));
        btnMAJ.setText(I18n.texte("button.MAJ"));
        btnVider.setText(I18n.texte("button.vider"));
        btnSupprimer.setText(I18n.texte("button.suprimer"));
        btnSupprimerStagiaire.setText(I18n.texte("button.suprimer"));
        btnChanger.setText(I18n.texte("button.changer"));
        btnImprimDoc.setText(I18n.texte("button.imprim"));
        homme.setText(I18n.texte("radio.homme"));
        femme.setText(I18n.texte("radio.femme"));
        apprentissage.setText(I18n.texte("radio.apprenti"));
        residentiel.setText(I18n.texte("radio.reside"));
        coursDeSoir.setText(I18n.texte("radio.cos"));
        lNom.setText(I18n.texte("label.nom"));
        lPrenom.setText(I18n.texte("label.prenom"));
        lDateLieu.setText(I18n.texte("label.dateLieuN"));
        lAdresse.setText(I18n.texte("label.adresse"));
        lTelephone.setText(I18n.texte("label.numero"));
        lEmail.setText(I18n.texte("label.email"));
        lMatricule.setText(I18n.texte("label.matricule"));
        lGroupe.setText(I18n.texte("label.groupe"));
        lMode.setText(I18n.texte("label.modeStage"));
        lMode2.setText(I18n.texte("label.modeStage"));
        lGenre.setText(I18n.texte("label.genre"));
        lInfoP.setText(I18n.texte("label.infoP"));
        lInfoS.setText(I18n.texte("label.infoS"));
        lFiltre.setText(I18n.texte("label.filtre"));
        fichier.setText(I18n.texte("menu.fichier"));
        tabExcel.setText(I18n.texte("menu.fichier.excel"));
        ficExcel.setText(I18n.texte("menu.fichier.csv"));
        aide.setText(I18n.texte("menu.aide"));
        langue.setText(I18n.texte("menu.langue"));
        aPropos.setText(I18n.texte("menu.aide.apr"));
        quitter.setText(I18n.texte("menu.aide.q"));
        nom.setToolTipText(I18n.texte("label.nom"));
        prenom.setToolTipText(I18n.texte("label.prenom"));
        lieu.setToolTipText(I18n.texte("tooltip.lieu"));
        numero.setToolTipText(I18n.texte("tooltip.numero"));
        matricule.setToolTipText(I18n.texte("label.matricule"));
        specialite.setToolTipText(I18n.texte("label.spec"));
        semestre.setToolTipText(I18n.texte("label.semestre"));
        groupe.setToolTipText(I18n.texte("label.groupe"));
        email.setToolTipText(I18n.texte("label.email"));
        adresse.setToolTipText(I18n.texte("label.adresse"));
        photo.setToolTipText(I18n.texte("tooltip.photo"));
        rechercher.setToolTipText(I18n.texte("tooltip.rec"));
        codeQr.setToolTipText(I18n.texte("tooltip.codeQr"));
        jScrollPane2.setToolTipText(I18n.texte("tooltip.liste"));
        textIndication();
        actualiserQr();
        if(getLocale().getLanguage().equalsIgnoreCase("ar")){
            applyComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        }else{
            applyComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
            
        }
    }
    public void textIndication(){
        nom.putClientProperty("JTextField.placeholderText", I18n.texte("prompt.nom"));
        prenom.putClientProperty("JTextField.placeholderText", I18n.texte("prompt.prenom"));
        lieu.putClientProperty("JTextField.placeholderText", I18n.texte("prompt.lieu"));
        specialite.putClientProperty("JTextField.placeholderText", I18n.texte("prompt.spec"));
        adresse.putClientProperty("JTextField.placeholderText", I18n.texte("prompt.adresse"));
        rechercher.putClientProperty("JTextField.placeholderText", I18n.texte("prompt.rec"));
        groupe.putClientProperty("JTextField.placeholderText", "14");
        semestre.putClientProperty("JTextField.placeholderText", "2");
        email.putClientProperty("JTextField.placeholderText", "garwisg@tizi.dz");
        matricule.putClientProperty("JTextField.placeholderText", "2121R4545");
        numero.putClientProperty("JTextField.placeholderText", "0559876543");
    }
}
