/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package View;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.image.BufferedImage;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.jdesktop.swingx.JXDatePicker;
import org.jdesktop.swingx.JXFormattedTextField;
import org.jdesktop.swingx.JXList;
import org.jdesktop.swingx.JXSearchField;
import org.jdesktop.swingx.JXTextField;
import outils.I18n;

/**
 *
 * @author Ould_Hamdi
 */
public class View extends javax.swing.JFrame {
    /** Creates new form View */
    public View() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeStage = new javax.swing.ButtonGroup();
        genre = new javax.swing.ButtonGroup();
        gesta = new javax.swing.JPanel();
        document = new javax.swing.JPanel();
        photo = new javax.swing.JPanel();
        lInfoP = new javax.swing.JLabel();
        lInfoS = new javax.swing.JLabel();
        btnChanger = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnEnregistrer = new javax.swing.JButton();
        btnVider = new javax.swing.JButton();
        codeQr = new javax.swing.JPanel();
        btnMAJ = new javax.swing.JButton();
        espaceNom = new javax.swing.JPanel();
        lNom = new javax.swing.JLabel();
        nom = new org.jdesktop.swingx.JXTextField();
        espacePrenom = new javax.swing.JPanel();
        lPrenom = new javax.swing.JLabel();
        prenom = new org.jdesktop.swingx.JXTextField();
        espaceTelephone = new javax.swing.JPanel();
        lTelephone = new javax.swing.JLabel();
        numero = new org.jdesktop.swingx.JXFormattedTextField();
        espaceAdresse = new javax.swing.JPanel();
        lAdresse = new javax.swing.JLabel();
        adresse = new org.jdesktop.swingx.JXTextField();
        espaceEmail = new javax.swing.JPanel();
        lEmail = new javax.swing.JLabel();
        email = new org.jdesktop.swingx.JXTextField();
        espaceSpecialite = new javax.swing.JPanel();
        lSpecialite2 = new javax.swing.JLabel();
        specialite = new org.jdesktop.swingx.JXTextField();
        espaceMatricule = new javax.swing.JPanel();
        lMatricule = new javax.swing.JLabel();
        matricule = new org.jdesktop.swingx.JXTextField();
        espaceModeStage = new javax.swing.JPanel();
        lMode = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        apprentissage = new javax.swing.JRadioButton();
        residentiel = new javax.swing.JRadioButton();
        coursDeSoir = new javax.swing.JRadioButton();
        espaceGroupe = new javax.swing.JPanel();
        lGroupe = new javax.swing.JLabel();
        groupe = new org.jdesktop.swingx.JXTextField();
        espaceSemestre = new javax.swing.JPanel();
        lSemestre2 = new javax.swing.JLabel();
        semestre = new org.jdesktop.swingx.JXTextField();
        espaceDateLieuNaissance = new javax.swing.JPanel();
        lDateLieu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        dateNaissance = new org.jdesktop.swingx.JXDatePicker();
        lieu = new org.jdesktop.swingx.JXTextField();
        espaceGenre = new javax.swing.JPanel();
        lGenre = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        femme = new javax.swing.JRadioButton();
        homme = new javax.swing.JRadioButton();
        btnImprimDoc = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listeStagiaire = new org.jdesktop.swingx.JXList();
        rechercher = new org.jdesktop.swingx.JXSearchField();
        lFiltre = new javax.swing.JLabel();
        btnSupprimerStagiaire = new javax.swing.JButton();
        espaceSemestre2 = new javax.swing.JPanel();
        lSemestre1 = new javax.swing.JLabel();
        listeSemestre = new javax.swing.JComboBox<>();
        espaceSpecialite2 = new javax.swing.JPanel();
        lSpecialite = new javax.swing.JLabel();
        listeSpecialite = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        fichier = new javax.swing.JMenu();
        tabExcel = new javax.swing.JMenuItem();
        ficExcel = new javax.swing.JMenuItem();
        langue = new javax.swing.JMenu();
        francais = new javax.swing.JMenuItem();
        arabe = new javax.swing.JMenuItem();
        aide = new javax.swing.JMenu();
        aPropos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        quitter = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gesta");
        setResizable(false);

        gesta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        document.setBackground(new java.awt.Color(0, 204, 204));
        document.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        photo.setToolTipText("Photo Profile");
        photo.setLayout(new java.awt.BorderLayout());
        document.add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 53, 210, 208));

        lInfoP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lInfoP.setText("Informations Personnel");
        document.add(lInfoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 17, -1, -1));

        lInfoS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lInfoS.setText("Informations Scolaire");
        document.add(lInfoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        btnChanger.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnChanger.setText("Changer");
        btnChanger.setMargin(new java.awt.Insets(2, 0, 3, 14));
        document.add(btnChanger, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 267, 77, -1));

        btnSupprimer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSupprimer.setText("Supprimer");
        document.add(btnSupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 267, -1, -1));

        btnEnregistrer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.setEnabled(false);
        document.add(btnEnregistrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 422, -1, -1));

        btnVider.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVider.setText("Vider Tout");
        document.add(btnVider, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 422, -1, -1));

        codeQr.setToolTipText("Code Qr");
        codeQr.setLayout(new java.awt.BorderLayout());
        document.add(codeQr, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 142, 140));

        btnMAJ.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMAJ.setText("Mettre a jour");
        btnMAJ.setEnabled(false);
        document.add(btnMAJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 422, -1, -1));

        espaceNom.setBackground(new java.awt.Color(0, 204, 204));

        lNom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lNom.setText("Nom:");
        espaceNom.add(lNom);

        nom.setToolTipText("Nom");
        nom.setPreferredSize(new java.awt.Dimension(230, 22));
        nom.setPrompt("Said Ghiles");
        espaceNom.add(nom);

        document.add(espaceNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 290, 33));

        espacePrenom.setBackground(new java.awt.Color(0, 204, 204));

        lPrenom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lPrenom.setText("Prenom:");
        espacePrenom.add(lPrenom);

        prenom.setToolTipText("Prenom");
        prenom.setPreferredSize(new java.awt.Dimension(230, 22));
        prenom.setPrompt("Garoui");
        espacePrenom.add(prenom);

        document.add(espacePrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 291, -1));

        espaceTelephone.setBackground(new java.awt.Color(0, 204, 204));

        lTelephone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lTelephone.setText("Telephone:");
        espaceTelephone.add(lTelephone);

        numero.setToolTipText("Numero Telephone");
        numero.setPreferredSize(new java.awt.Dimension(220, 22));
        numero.setPrompt("0559876543");
        espaceTelephone.add(numero);

        document.add(espaceTelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 300, 30));

        espaceAdresse.setBackground(new java.awt.Color(0, 204, 204));

        lAdresse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lAdresse.setText("Adresse:");
        espaceAdresse.add(lAdresse);

        adresse.setToolTipText("adresse");
        adresse.setPreferredSize(new java.awt.Dimension(220, 22));
        adresse.setPrompt("Tizi-Takjda-W.TiziOuzou");
        espaceAdresse.add(adresse);

        document.add(espaceAdresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 320, 30));

        espaceEmail.setBackground(new java.awt.Color(0, 204, 204));

        lEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lEmail.setText("Email:");
        espaceEmail.add(lEmail);

        email.setToolTipText("Email");
        email.setPreferredSize(new java.awt.Dimension(220, 22));
        email.setPrompt("garwisg@tizi.dz");
        espaceEmail.add(email);

        document.add(espaceEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 290, 30));

        espaceSpecialite.setBackground(new java.awt.Color(0, 204, 204));

        lSpecialite2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lSpecialite2.setText("Specialite:");
        espaceSpecialite.add(lSpecialite2);

        specialite.setToolTipText("Specialite");
        specialite.setPreferredSize(new java.awt.Dimension(170, 22));
        specialite.setPrompt("Developpeur AMP");
        espaceSpecialite.add(specialite);

        document.add(espaceSpecialite, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 250, 30));

        espaceMatricule.setBackground(new java.awt.Color(0, 204, 204));

        lMatricule.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lMatricule.setText("Matricule:");
        espaceMatricule.add(lMatricule);

        matricule.setToolTipText("Matricule");
        matricule.setPreferredSize(new java.awt.Dimension(170, 22));
        matricule.setPrompt("matcl2526");
        espaceMatricule.add(matricule);

        document.add(espaceMatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 260, 30));

        espaceModeStage.setBackground(new java.awt.Color(0, 204, 204));

        lMode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lMode.setText("Mode Stage:");
        espaceModeStage.add(lMode);

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));

        apprentissage.setBackground(new java.awt.Color(0, 204, 204));
        modeStage.add(apprentissage);
        apprentissage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        apprentissage.setText("Apprentissage");
        apprentissage.setActionCommand("apprentissage");
        jPanel4.add(apprentissage);

        residentiel.setBackground(new java.awt.Color(0, 204, 204));
        modeStage.add(residentiel);
        residentiel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        residentiel.setText("Residentiel");
        residentiel.setActionCommand("residentiel");
        jPanel4.add(residentiel);

        coursDeSoir.setBackground(new java.awt.Color(0, 204, 204));
        modeStage.add(coursDeSoir);
        coursDeSoir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        coursDeSoir.setText("Cours de Soir");
        coursDeSoir.setActionCommand("cours de Soir");
        jPanel4.add(coursDeSoir);

        espaceModeStage.add(jPanel4);

        document.add(espaceModeStage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 391, 390, 30));

        espaceGroupe.setBackground(new java.awt.Color(0, 204, 204));

        lGroupe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lGroupe.setText("Groupe:");
        espaceGroupe.add(lGroupe);

        groupe.setToolTipText("Groupe");
        groupe.setPrompt("14");
        espaceGroupe.add(groupe);

        document.add(espaceGroupe, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 130, 30));

        espaceSemestre.setBackground(new java.awt.Color(0, 204, 204));

        lSemestre2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lSemestre2.setText("Semestre:");
        espaceSemestre.add(lSemestre2);

        semestre.setToolTipText("Semestre");
        semestre.setPrompt("2");
        espaceSemestre.add(semestre);

        document.add(espaceSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 140, 30));

        espaceDateLieuNaissance.setBackground(new java.awt.Color(0, 204, 204));

        lDateLieu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lDateLieu.setText("Date-Lieu Naissance:");
        espaceDateLieuNaissance.add(lDateLieu);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.add(dateNaissance);

        lieu.setToolTipText("Lieu de Naissance");
        lieu.setPrompt("Tizi-Ouzou");
        jPanel1.add(lieu);

        espaceDateLieuNaissance.add(jPanel1);

        document.add(espaceDateLieuNaissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 390, 40));

        espaceGenre.setBackground(new java.awt.Color(0, 204, 204));

        lGenre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lGenre.setText("Genre:");
        espaceGenre.add(lGenre);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        femme.setBackground(new java.awt.Color(0, 204, 204));
        genre.add(femme);
        femme.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        femme.setText("Femme");
        femme.setActionCommand("femme");
        jPanel2.add(femme);

        homme.setBackground(new java.awt.Color(0, 204, 204));
        genre.add(homme);
        homme.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        homme.setText("Homme");
        homme.setActionCommand("homme");
        homme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hommeActionPerformed(evt);
            }
        });
        jPanel2.add(homme);

        espaceGenre.add(jPanel2);

        document.add(espaceGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 220, 30));

        gesta.add(document, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 57, 650, 458));

        btnImprimDoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnImprimDoc.setText("Imprimer document");
        btnImprimDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimDocActionPerformed(evt);
            }
        });
        gesta.add(btnImprimDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 28, -1, -1));

        listeStagiaire.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listeStagiaire.setToolTipText("Liste des Stagiaires");
        listeStagiaire.setAutoCreateRowSorter(true);
        listeStagiaire.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jScrollPane2.setViewportView(listeStagiaire);

        gesta.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 112, 207, 393));

        rechercher.setToolTipText("Trouver un Stagiaire");
        rechercher.setPrompt("Ghiles Garoui");
        gesta.add(rechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 83, 132, -1));

        lFiltre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lFiltre.setText("Filtrer par");
        gesta.add(lFiltre, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 6, -1, -1));

        btnSupprimerStagiaire.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnSupprimerStagiaire.setText("Supprimer");
        btnSupprimerStagiaire.setEnabled(false);
        btnSupprimerStagiaire.setMargin(new java.awt.Insets(2, 0, 3, 14));
        btnSupprimerStagiaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerStagiaireActionPerformed(evt);
            }
        });
        gesta.add(btnSupprimerStagiaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 85, 69, -1));

        lSemestre1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lSemestre1.setText("Semestre:");
        espaceSemestre2.add(lSemestre1);

        espaceSemestre2.add(listeSemestre);

        gesta.add(espaceSemestre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 150, 30));

        lSpecialite.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lSpecialite.setText("Specialite:");
        espaceSpecialite2.add(lSpecialite);

        espaceSpecialite2.add(listeSpecialite);

        gesta.add(espaceSpecialite2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 160, 30));

        fichier.setText("Fichier");

        tabExcel.setText("Exporter la liste en tableau Excel");
        fichier.add(tabExcel);

        ficExcel.setText("Importer une liste Excel");
        fichier.add(ficExcel);

        jMenuBar1.add(fichier);

        langue.setText("Langue");
        langue.setToolTipText("");

        francais.setText("Francais");
        langue.add(francais);

        arabe.setText("العربية");
        langue.add(arabe);

        jMenuBar1.add(langue);

        aide.setText("Aide");

        aPropos.setText("A propos");
        aide.add(aPropos);
        aide.add(jSeparator1);

        quitter.setText("Quitter");
        aide.add(quitter);

        jMenuBar1.add(aide);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimDocActionPerformed

    private void btnSupprimerStagiaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerStagiaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSupprimerStagiaireActionPerformed

    private void hommeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hommeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hommeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aPropos;
    private org.jdesktop.swingx.JXTextField adresse;
    private javax.swing.JMenu aide;
    private javax.swing.JRadioButton apprentissage;
    private javax.swing.JMenuItem arabe;
    private javax.swing.JButton btnChanger;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JButton btnImprimDoc;
    private javax.swing.JButton btnMAJ;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnSupprimerStagiaire;
    private javax.swing.JButton btnVider;
    private javax.swing.JPanel codeQr;
    private javax.swing.JRadioButton coursDeSoir;
    private org.jdesktop.swingx.JXDatePicker dateNaissance;
    private javax.swing.JPanel document;
    private org.jdesktop.swingx.JXTextField email;
    private javax.swing.JPanel espaceAdresse;
    private javax.swing.JPanel espaceDateLieuNaissance;
    private javax.swing.JPanel espaceEmail;
    private javax.swing.JPanel espaceGenre;
    private javax.swing.JPanel espaceGroupe;
    private javax.swing.JPanel espaceMatricule;
    private javax.swing.JPanel espaceModeStage;
    private javax.swing.JPanel espaceNom;
    private javax.swing.JPanel espacePrenom;
    private javax.swing.JPanel espaceSemestre;
    private javax.swing.JPanel espaceSemestre2;
    private javax.swing.JPanel espaceSpecialite;
    private javax.swing.JPanel espaceSpecialite2;
    private javax.swing.JPanel espaceTelephone;
    private javax.swing.JRadioButton femme;
    private javax.swing.JMenuItem ficExcel;
    private javax.swing.JMenu fichier;
    private javax.swing.JMenuItem francais;
    private javax.swing.ButtonGroup genre;
    private javax.swing.JPanel gesta;
    private org.jdesktop.swingx.JXTextField groupe;
    private javax.swing.JRadioButton homme;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lAdresse;
    private javax.swing.JLabel lDateLieu;
    private javax.swing.JLabel lEmail;
    private javax.swing.JLabel lFiltre;
    private javax.swing.JLabel lGenre;
    private javax.swing.JLabel lGroupe;
    private javax.swing.JLabel lInfoP;
    private javax.swing.JLabel lInfoS;
    private javax.swing.JLabel lMatricule;
    private javax.swing.JLabel lMode;
    private javax.swing.JLabel lNom;
    private javax.swing.JLabel lPrenom;
    private javax.swing.JLabel lSemestre1;
    private javax.swing.JLabel lSemestre2;
    private javax.swing.JLabel lSpecialite;
    private javax.swing.JLabel lSpecialite2;
    private javax.swing.JLabel lTelephone;
    private javax.swing.JMenu langue;
    private org.jdesktop.swingx.JXTextField lieu;
    private javax.swing.JComboBox<String> listeSemestre;
    private javax.swing.JComboBox<String> listeSpecialite;
    private org.jdesktop.swingx.JXList listeStagiaire;
    private org.jdesktop.swingx.JXTextField matricule;
    private javax.swing.ButtonGroup modeStage;
    private org.jdesktop.swingx.JXTextField nom;
    private org.jdesktop.swingx.JXFormattedTextField numero;
    private javax.swing.JPanel photo;
    private org.jdesktop.swingx.JXTextField prenom;
    private javax.swing.JMenuItem quitter;
    private org.jdesktop.swingx.JXSearchField rechercher;
    private javax.swing.JRadioButton residentiel;
    private org.jdesktop.swingx.JXTextField semestre;
    private org.jdesktop.swingx.JXTextField specialite;
    private javax.swing.JMenuItem tabExcel;
    // End of variables declaration//GEN-END:variables

    public JXTextField getAdresse() {
        return adresse;
    }





    public JButton getBtnChanger() {
        return btnChanger;
    }

    public JButton getBtnEnregistrer() {
        return btnEnregistrer;
    }


    public JButton getBtnImprimDoc() {
        return btnImprimDoc;
    }

    public JButton getBtnSupprimer() {
        return btnSupprimer;
    }

    public JButton getBtnVider() {
        return btnVider;
    }

    public JXTextField getEmail() {
        return email;
    }

    public ButtonGroup getGenre() {
        return genre;
    }

    public JXTextField getGroupe() {
        return groupe;
    }



    public JTextField getLieu() {
        return lieu;
    }

    public JXList getListeStagiaire() {
        return listeStagiaire;
    }

    public JXTextField getMatricule() {
        return matricule;
    }

    public ButtonGroup getModeStage() {
        return modeStage;
    }


    public JXTextField getNom() {
        return nom;
    }

    public JPanel getPhoto() {
        return photo;
    }

    public JXTextField getPrenom() {
        return prenom;
    }

    public JXSearchField getRechercher() {
        return rechercher;
    }

    public JXTextField getSemestre() {
        return semestre;
    }

    public JXTextField getSpecialite() {
        return specialite;
    }

    public JXFormattedTextField getTelephone() {
        return numero;
    }

    public void setPhoto(JPanel photo) {
        this.photo = photo;
    }

    public JPanel getCodeQr() {
        return codeQr;
    }

    public JXDatePicker getDateNaissance() {
        return dateNaissance;
    }
    DocumentListener laisserSauvegarder=new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
         laisserSauvegarder();}

        @Override
        public void removeUpdate(DocumentEvent e) {
         laisserSauvegarder();}

        @Override
        public void changedUpdate(DocumentEvent e) {
            laisserSauvegarder();
        }
    };
    private void laisserSauvegarder(){
        btnEnregistrer.setEnabled(
                !nom.getText().isEmpty() && !prenom.getText().isEmpty() && !lieu.getText().isEmpty() &&
                !matricule.getText().isEmpty() && !semestre.getText().isEmpty() && !specialite.getText().isEmpty() &&
                genre.getSelection()!=null && modeStage.getSelection()!=null&& dateNaissance.getDate()!=null
        );
        btnMAJ.setEnabled(
                !nom.getText().isEmpty() && !prenom.getText().isEmpty() && !lieu.getText().isEmpty() &&
                !matricule.getText().isEmpty() && !semestre.getText().isEmpty() && !specialite.getText().isEmpty() &&
                genre.getSelection()!=null && modeStage.getSelection()!=null&& dateNaissance.getDate()!=null
        );
        actualiserQr();
    }
    public void actualiserQr(){
        String text="""
                    %s%s
                    %s%s
                    %s %s - %s
                    %s%s
                    %s%s
                    %s%s
                    """.formatted(
                    lNom.getText(),nom.getText(),
                    lPrenom.getText(),prenom.getText(),
                    lDateLieu.getText(),
                    (dateNaissance.getDate()!=null)
                    ?new SimpleDateFormat("dd-MM-yyyy").format(dateNaissance.getDate())
                    :null,
                    lieu.getText(),
                    lSpecialite.getText(),specialite.getText(),
                    lSemestre1.getText(),semestre.getText(),
                    lMatricule.getText(),matricule.getText()
                    );
        
        if(!text.isEmpty()){
            try{
                BufferedImage qr=genererQr(text);
                if(qr!=null){
                    JLabel image=new JLabel(new ImageIcon(qr));
                    codeQr.removeAll();
                    codeQr.add(image,BorderLayout.CENTER);
                    codeQr.revalidate();
                    codeQr.repaint();
                }
            }catch(Exception e){
                
            }
        }
    }
    public BufferedImage genererQr(String texte){
        QRCodeWriter qrW=new QRCodeWriter();
        try {
            Map<EncodeHintType,Object> encoderUTF8=new HashMap<>();
            encoderUTF8.put(EncodeHintType.CHARACTER_SET, "UTF-8");
            BitMatrix matrice=qrW.encode(texte, BarcodeFormat.QR_CODE, codeQr.getBounds().width, codeQr.getBounds().height,encoderUTF8);
            return MatrixToImageWriter.toBufferedImage(matrice);
        } catch (WriterException ex) {
            return null;
        }
        
    }
    public void ajouterDocumentListener(){
        nom.getDocument().addDocumentListener(laisserSauvegarder);
        prenom.getDocument().addDocumentListener(laisserSauvegarder);
        matricule.getDocument().addDocumentListener(laisserSauvegarder);
        semestre.getDocument().addDocumentListener(laisserSauvegarder);
        specialite.getDocument().addDocumentListener(laisserSauvegarder);
        groupe.getDocument().addDocumentListener(laisserSauvegarder);
        lieu.getDocument().addDocumentListener(laisserSauvegarder);
        homme.addActionListener(e->{
            laisserSauvegarder();
        });
        femme.addActionListener(e->{
            laisserSauvegarder();
        });
        residentiel.addActionListener(e->{
            laisserSauvegarder();
        });
        apprentissage.addActionListener(e->{
            laisserSauvegarder();
        });
        coursDeSoir.addActionListener(e->{
            laisserSauvegarder();
        });
        dateNaissance.addActionListener(e->{
            laisserSauvegarder();
    });
    }

    public JComboBox<String> getListeSemestre() {
        return listeSemestre;
    }

    public JComboBox<String> getListeSpecialite() {
        return listeSpecialite;
    }

    public JButton getBtnMAJ() {
        return btnMAJ;
    }

    public JButton getBtnSupprimerStagiaire() {
        return btnSupprimerStagiaire;
    }

    public JPanel getDocument() {
        return document;
    }

    public JMenuItem getaPropos() {
        return aPropos;
    }

    

    public JMenuItem getQuitter() {
        return quitter;
    }

    public JMenuItem getArabe() {
        return arabe;
    }

    public JMenuItem getFrancais() {
        return francais;
    }

    public JMenuItem getTabExcel() {
        return tabExcel;
    }

    public JMenuItem getFicExcel() {
        return ficExcel;
    }
    
    public void appliquerLangue(){
        lSemestre1.setText(I18n.texte("label.semestre"));
        lSemestre2.setText(I18n.texte("label.semestre"));
        lSpecialite.setText(I18n.texte("label.spec"));
        lSpecialite2.setText(I18n.texte("label.spec"));
        setTitle(I18n.texte("titre"));
        btnEnregistrer.setText(I18n.texte("button.enregistrer"));
        btnMAJ.setText(I18n.texte("button.MAJ"));
        btnVider.setText(I18n.texte("button.vider"));
        btnSupprimer.setText(I18n.texte("button.suprimer"));
        btnSupprimerStagiaire.setText(I18n.texte("button.suprimer"));
        btnChanger.setText(I18n.texte("button.changer"));
        btnImprimDoc.setText(I18n.texte("button.imprim"));
        homme.setText(I18n.texte("radio.homme"));
        femme.setText(I18n.texte("radio.femme"));
        apprentissage.setText(I18n.texte("radio.apprenti"));
        residentiel.setText(I18n.texte("radio.reside"));
        coursDeSoir.setText(I18n.texte("radio.cos"));
        lNom.setText(I18n.texte("label.nom"));
        lPrenom.setText(I18n.texte("label.prenom"));
        lDateLieu.setText(I18n.texte("label.dateLieuN"));
        lAdresse.setText(I18n.texte("label.adresse"));
        lTelephone.setText(I18n.texte("label.numero"));
        lEmail.setText(I18n.texte("label.email"));
        lMatricule.setText(I18n.texte("label.matricule"));
        lGroupe.setText(I18n.texte("label.groupe"));
        lMode.setText(I18n.texte("label.modeStage"));
        lGenre.setText(I18n.texte("label.genre"));
        lInfoP.setText(I18n.texte("label.infoP"));
        lInfoS.setText(I18n.texte("label.infoS"));
        lFiltre.setText(I18n.texte("label.filtre"));
        fichier.setText(I18n.texte("menu.fichier"));
        tabExcel.setText(I18n.texte("menu.fichier.excel"));
        ficExcel.setText(I18n.texte("menu.fichier.csv"));
        aide.setText(I18n.texte("menu.aide"));
        langue.setText(I18n.texte("menu.langue"));
        aPropos.setText(I18n.texte("menu.aide.apr"));
        quitter.setText(I18n.texte("menu.aide.q"));
        nom.setToolTipText(I18n.texte("label.nom"));
        prenom.setToolTipText(I18n.texte("label.prenom"));
        lieu.setToolTipText(I18n.texte("tooltip.lieu"));
        numero.setToolTipText(I18n.texte("tooltip.numero"));
        matricule.setToolTipText(I18n.texte("label.matricule"));
        specialite.setToolTipText(I18n.texte("label.spec"));
        semestre.setToolTipText(I18n.texte("label.semestre"));
        groupe.setToolTipText(I18n.texte("label.groupe"));
        email.setToolTipText(I18n.texte("label.email"));
        adresse.setToolTipText(I18n.texte("label.adresse"));
        photo.setToolTipText(I18n.texte("tooltip.photo"));
        rechercher.setToolTipText(I18n.texte("tooltip.rec"));
        codeQr.setToolTipText(I18n.texte("tooltip.codeQr"));
        listeStagiaire.setToolTipText(I18n.texte("tooltip.liste"));
        
        echangerPlace(espaceNom);
        echangerPlace(espacePrenom);
        echangerPlace(espaceDateLieuNaissance);
        echangerPlace(espaceTelephone);
        echangerPlace(espaceEmail);
        echangerPlace(espaceAdresse);
        echangerPlace(espaceMatricule);
        echangerPlace(espaceSemestre);
        echangerPlace(espaceSemestre2);
        echangerPlace(espaceSpecialite);
        echangerPlace(espaceSpecialite2);
        echangerPlace(espaceGenre);
        echangerPlace(espaceGroupe);
        echangerPlace(espaceModeStage);
        actualiserQr();
    }
    private void echangerPlace(JPanel espace){
        Component[] composant=espace.getComponents();
        espace.remove(composant[0]);
        espace.add(composant[0]);
        espace.revalidate();
        espace.repaint();
        

    }
}
