/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package View;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.jdesktop.swingx.JXDatePicker;
import org.jdesktop.swingx.JXFormattedTextField;
import org.jdesktop.swingx.JXList;
import org.jdesktop.swingx.JXSearchField;
import org.jdesktop.swingx.JXTextField;

/**
 *
 * @author Ould_Hamdi
 */
public class View extends javax.swing.JFrame {
    /** Creates new form View */
    public View() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeStage = new javax.swing.ButtonGroup();
        genre = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        document = new javax.swing.JPanel();
        photo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        femme = new javax.swing.JRadioButton();
        homme = new javax.swing.JRadioButton();
        apprentissage = new javax.swing.JRadioButton();
        residentiel = new javax.swing.JRadioButton();
        coursDeSoir = new javax.swing.JRadioButton();
        btnChanger = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnEnregistrer = new javax.swing.JButton();
        btnVider = new javax.swing.JButton();
        codeQr = new javax.swing.JPanel();
        dateNaissance = new org.jdesktop.swingx.JXDatePicker();
        email = new org.jdesktop.swingx.JXTextField();
        nom = new org.jdesktop.swingx.JXTextField();
        prenom = new org.jdesktop.swingx.JXTextField();
        adresse = new org.jdesktop.swingx.JXTextField();
        numero = new org.jdesktop.swingx.JXFormattedTextField();
        matricule = new org.jdesktop.swingx.JXTextField();
        specialite = new org.jdesktop.swingx.JXTextField();
        semestre = new org.jdesktop.swingx.JXTextField();
        groupe = new org.jdesktop.swingx.JXTextField();
        lieu = new org.jdesktop.swingx.JXTextField();
        btnMAJ = new javax.swing.JButton();
        btnImprimDoc = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listeStagiaire = new org.jdesktop.swingx.JXList();
        rechercher = new org.jdesktop.swingx.JXSearchField();
        jLabel9 = new javax.swing.JLabel();
        listeSemestre = new javax.swing.JComboBox<>();
        listeSpecialite = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnSupprimerStagiaire = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Stagiaire");

        document.setBackground(new java.awt.Color(0, 204, 204));

        photo.setToolTipText("Photo Profile");
        photo.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Informations Personnel");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nom:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Adresse:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Prenom:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Informations Scolaire");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Genre:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Date-Lieu Naissance:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Telephone:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Email:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Mode Stage:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Matricule:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Specialite:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Semestre:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Groupe:");

        femme.setBackground(new java.awt.Color(0, 204, 204));
        genre.add(femme);
        femme.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        femme.setText("Femme");
        femme.setActionCommand("femme");

        homme.setBackground(new java.awt.Color(0, 204, 204));
        genre.add(homme);
        homme.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        homme.setText("Homme");
        homme.setActionCommand("homme");

        apprentissage.setBackground(new java.awt.Color(0, 204, 204));
        modeStage.add(apprentissage);
        apprentissage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        apprentissage.setText("Apprentissage");
        apprentissage.setActionCommand("apprentissage");

        residentiel.setBackground(new java.awt.Color(0, 204, 204));
        modeStage.add(residentiel);
        residentiel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        residentiel.setText("Residentiel");
        residentiel.setActionCommand("residentiel");

        coursDeSoir.setBackground(new java.awt.Color(0, 204, 204));
        modeStage.add(coursDeSoir);
        coursDeSoir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        coursDeSoir.setText("Cours de Soir");
        coursDeSoir.setActionCommand("cours de Soir");

        btnChanger.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnChanger.setText("Changer");
        btnChanger.setMargin(new java.awt.Insets(2, 0, 3, 14));

        btnSupprimer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSupprimer.setText("Supprimer");

        btnEnregistrer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.setEnabled(false);

        btnVider.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVider.setText("Vider Tout");

        codeQr.setToolTipText("Code Qr");
        codeQr.setLayout(new java.awt.BorderLayout());

        email.setToolTipText("Email");
        email.setPrompt("garwisg@tizi.dz");

        nom.setToolTipText("Nom");
        nom.setPrompt("Said Ghiles");

        prenom.setToolTipText("Prenom");
        prenom.setPrompt("Garoui");

        adresse.setToolTipText("adresse");
        adresse.setPrompt("Tizi-Takjda-W.TiziOuzou");

        numero.setToolTipText("Numero Telephone");
        numero.setPrompt("05-59876543");

        matricule.setToolTipText("Matricule");
        matricule.setPrompt("matcl2526");

        specialite.setToolTipText("Specialite");
        specialite.setPrompt("Developpeur AMP");

        semestre.setToolTipText("Semestre");
        semestre.setPrompt("2");

        groupe.setToolTipText("Groupe");
        groupe.setPrompt("14");

        lieu.setToolTipText("Lieu de Naissance");
        lieu.setPrompt("Tizi-Ouzou");

        btnMAJ.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMAJ.setText("Mettre a jour");
        btnMAJ.setEnabled(false);

        javax.swing.GroupLayout documentLayout = new javax.swing.GroupLayout(document);
        document.setLayout(documentLayout);
        documentLayout.setHorizontalGroup(
            documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, documentLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(documentLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnVider)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(documentLayout.createSequentialGroup()
                        .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, documentLayout.createSequentialGroup()
                                .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(documentLayout.createSequentialGroup()
                                        .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(documentLayout.createSequentialGroup()
                                                .addComponent(semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(groupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(documentLayout.createSequentialGroup()
                                                .addComponent(residentiel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(documentLayout.createSequentialGroup()
                                                        .addComponent(btnEnregistrer)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(btnMAJ))
                                                    .addGroup(documentLayout.createSequentialGroup()
                                                        .addComponent(apprentissage)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(coursDeSoir))))))
                                    .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, documentLayout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(specialite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(documentLayout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(matricule, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(documentLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(documentLayout.createSequentialGroup()
                                        .addComponent(btnChanger, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSupprimer))
                                    .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(documentLayout.createSequentialGroup()
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, documentLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))))
                        .addGap(18, 18, 18)))
                .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(documentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(homme)
                        .addGap(28, 28, 28)
                        .addComponent(femme)
                        .addGap(104, 104, 104))
                    .addGroup(documentLayout.createSequentialGroup()
                        .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adresse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(documentLayout.createSequentialGroup()
                                .addComponent(dateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(lieu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(prenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(codeQr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, documentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(254, 254, 254))
        );
        documentLayout.setVerticalGroup(
            documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(documentLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(documentLayout.createSequentialGroup()
                        .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(documentLayout.createSequentialGroup()
                                .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(dateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(femme)
                                    .addComponent(homme))
                                .addGap(18, 18, 18)
                                .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63))
                            .addGroup(documentLayout.createSequentialGroup()
                                .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, documentLayout.createSequentialGroup()
                        .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(documentLayout.createSequentialGroup()
                        .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(documentLayout.createSequentialGroup()
                                .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(btnChanger)
                                    .addComponent(btnSupprimer))
                                .addGap(9, 9, 9)
                                .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(matricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(specialite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(groupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(apprentissage, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(residentiel)
                            .addComponent(coursDeSoir, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVider)
                            .addGroup(documentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnEnregistrer)
                                .addComponent(btnMAJ))))
                    .addComponent(codeQr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnImprimDoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnImprimDoc.setText("Imprimer document");
        btnImprimDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimDocActionPerformed(evt);
            }
        });

        listeStagiaire.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listeStagiaire.setToolTipText("Liste des Stagiaires");
        listeStagiaire.setAutoCreateRowSorter(true);
        listeStagiaire.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jScrollPane2.setViewportView(listeStagiaire);

        rechercher.setToolTipText("Trouver un Stagiaire");
        rechercher.setPrompt("Ghiles Garoui");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Filtrer par");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Semestre:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Specialite:");

        btnSupprimerStagiaire.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnSupprimerStagiaire.setText("Supprimer");
        btnSupprimerStagiaire.setEnabled(false);
        btnSupprimerStagiaire.setMargin(new java.awt.Insets(2, 0, 3, 14));
        btnSupprimerStagiaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerStagiaireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel16)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnSupprimerStagiaire, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rechercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listeSemestre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(listeSpecialite, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImprimDoc)
                    .addComponent(document, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimDoc)
                    .addComponent(listeSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(listeSpecialite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSupprimerStagiaire))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(document, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimDocActionPerformed

    private void btnSupprimerStagiaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerStagiaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSupprimerStagiaireActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXTextField adresse;
    private javax.swing.JRadioButton apprentissage;
    private javax.swing.JButton btnChanger;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JButton btnImprimDoc;
    private javax.swing.JButton btnMAJ;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton btnSupprimerStagiaire;
    private javax.swing.JButton btnVider;
    private javax.swing.JPanel codeQr;
    private javax.swing.JRadioButton coursDeSoir;
    private org.jdesktop.swingx.JXDatePicker dateNaissance;
    private javax.swing.JPanel document;
    private org.jdesktop.swingx.JXTextField email;
    private javax.swing.JRadioButton femme;
    private javax.swing.ButtonGroup genre;
    private org.jdesktop.swingx.JXTextField groupe;
    private javax.swing.JRadioButton homme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXTextField lieu;
    private javax.swing.JComboBox<String> listeSemestre;
    private javax.swing.JComboBox<String> listeSpecialite;
    private org.jdesktop.swingx.JXList listeStagiaire;
    private org.jdesktop.swingx.JXTextField matricule;
    private javax.swing.ButtonGroup modeStage;
    private org.jdesktop.swingx.JXTextField nom;
    private org.jdesktop.swingx.JXFormattedTextField numero;
    private javax.swing.JPanel photo;
    private org.jdesktop.swingx.JXTextField prenom;
    private org.jdesktop.swingx.JXSearchField rechercher;
    private javax.swing.JRadioButton residentiel;
    private org.jdesktop.swingx.JXTextField semestre;
    private org.jdesktop.swingx.JXTextField specialite;
    // End of variables declaration//GEN-END:variables

    public JXTextField getAdresse() {
        return adresse;
    }





    public JButton getBtnChanger() {
        return btnChanger;
    }

    public JButton getBtnEnregistrer() {
        return btnEnregistrer;
    }


    public JButton getBtnImprimDoc() {
        return btnImprimDoc;
    }

    public JButton getBtnSupprimer() {
        return btnSupprimer;
    }

    public JButton getBtnVider() {
        return btnVider;
    }

    public JXTextField getEmail() {
        return email;
    }

    public ButtonGroup getGenre() {
        return genre;
    }

    public JXTextField getGroupe() {
        return groupe;
    }



    public JTextField getLieu() {
        return lieu;
    }

    public JXList getListeStagiaire() {
        return listeStagiaire;
    }

    public JXTextField getMatricule() {
        return matricule;
    }

    public ButtonGroup getModeStage() {
        return modeStage;
    }


    public JXTextField getNom() {
        return nom;
    }

    public JPanel getPhoto() {
        return photo;
    }

    public JXTextField getPrenom() {
        return prenom;
    }

    public JXSearchField getRechercher() {
        return rechercher;
    }

    public JXTextField getSemestre() {
        return semestre;
    }

    public JXTextField getSpecialite() {
        return specialite;
    }

    public JXFormattedTextField getTelephone() {
        return numero;
    }

    public void setPhoto(JPanel photo) {
        this.photo = photo;
    }

    public JPanel getCodeQr() {
        return codeQr;
    }

    public JXDatePicker getDateNaissance() {
        return dateNaissance;
    }
    DocumentListener laisserSauvegarder=new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
         laisserSauvegarder();}

        @Override
        public void removeUpdate(DocumentEvent e) {
         laisserSauvegarder();}

        @Override
        public void changedUpdate(DocumentEvent e) {
            laisserSauvegarder();
        }
    };
    private void laisserSauvegarder(){
        btnEnregistrer.setEnabled(
                !nom.getText().isEmpty() && !prenom.getText().isEmpty() && !lieu.getText().isEmpty() &&
                !matricule.getText().isEmpty() && !semestre.getText().isEmpty() && !specialite.getText().isEmpty() &&
                genre.getSelection()!=null && modeStage.getSelection()!=null&& dateNaissance.getDate()!=null
        );
        btnMAJ.setEnabled(
                !nom.getText().isEmpty() && !prenom.getText().isEmpty() && !lieu.getText().isEmpty() &&
                !matricule.getText().isEmpty() && !semestre.getText().isEmpty() && !specialite.getText().isEmpty() &&
                genre.getSelection()!=null && modeStage.getSelection()!=null&& dateNaissance.getDate()!=null
        );
        actualiserQr();
    }
    public void actualiserQr(){
        String text="""
                    Nom:%s
                    Prenom:%s
                    Date et Lieu de Naissance:%s a %s
                    Specialite:%s
                    Semestre:%s
                    Matricule:%s
                    """.formatted(
                    nom.getText(),prenom.getText(),
                    (dateNaissance.getDate()!=null)
                    ?dateNaissance.getDate().getDay()+"/"+dateNaissance.getDate().getMonth()+"/"+dateNaissance.getDate().getYear()
                    :null,
                    lieu.getText(),
                    specialite.getText(),
                    semestre.getText(),matricule.getText()
                    );
        
        if(!text.isEmpty()){
            try{
                BufferedImage qr=genererQr(text);
                if(qr!=null){
                    JLabel image=new JLabel(new ImageIcon(qr));
                    codeQr.removeAll();
                    codeQr.add(image,BorderLayout.CENTER);
                    codeQr.revalidate();
                    codeQr.repaint();
                }
            }catch(Exception e){
                
            }
        }
    }
    public BufferedImage genererQr(String texte){
        QRCodeWriter qrW=new QRCodeWriter();
        try {
            BitMatrix matrice=qrW.encode(texte, BarcodeFormat.QR_CODE, codeQr.getBounds().width, codeQr.getBounds().height);
            return MatrixToImageWriter.toBufferedImage(matrice);
        } catch (WriterException ex) {
            return null;
        }
        
    }
    public void ajouterDocumentListener(){
        nom.getDocument().addDocumentListener(laisserSauvegarder);
        prenom.getDocument().addDocumentListener(laisserSauvegarder);
        matricule.getDocument().addDocumentListener(laisserSauvegarder);
        semestre.getDocument().addDocumentListener(laisserSauvegarder);
        specialite.getDocument().addDocumentListener(laisserSauvegarder);
        groupe.getDocument().addDocumentListener(laisserSauvegarder);
        lieu.getDocument().addDocumentListener(laisserSauvegarder);
        homme.addActionListener(e->{
            laisserSauvegarder();
        });
        femme.addActionListener(e->{
            laisserSauvegarder();
        });
        residentiel.addActionListener(e->{
            laisserSauvegarder();
        });
        apprentissage.addActionListener(e->{
            laisserSauvegarder();
        });
        coursDeSoir.addActionListener(e->{
            laisserSauvegarder();
        });
        dateNaissance.addActionListener(e->{
            laisserSauvegarder();
    });
    }

//    public JRadioButton getApprentissage() {
//        return apprentissage;
//    }
//
//    public JRadioButton getCoursDeSoir() {
//        return coursDeSoir;
//    }
//
//    public JRadioButton getFemme() {
//        return femme;
//    }
//
//    public JRadioButton getHomme() {
//        return homme;
//    }
//
//    public JRadioButton getResidentiel() {
//        return residentiel;
//    }

    public JComboBox<String> getListeSemestre() {
        return listeSemestre;
    }

    public JComboBox<String> getListeSpecialite() {
        return listeSpecialite;
    }

    public JButton getBtnMAJ() {
        return btnMAJ;
    }

    public JButton getBtnSupprimerStagiaire() {
        return btnSupprimerStagiaire;
    }

    public JPanel getDocument() {
        return document;
    }

    
}
