/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package outils;

import View.View;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.SwingWorker;
import model.Model;
import model.Stagiaire;

/**
 *
 * @author Malick
 */
public class ProgressionSuppression extends javax.swing.JDialog {

    /**
     * Creates new form ProgressionSuppression
     */
    View parent;
    Model model;
    DefaultListModel<Stagiaire> liste;
    Supprimer supprimer;
    ArrayList<Stagiaire> supprimerDeLaListe;
    ArrayList<Stagiaire> supprimerDeLaBD;
    public ProgressionSuppression(View parent, boolean modal,Model model,DefaultListModel<Stagiaire> liste,String titre) {
        super(parent, modal);
        this.parent=parent;
        this.model=model;
        this.liste=liste;
        initComponents();
        setTitle(titre);
        btnAnnuler.setText(I18n.texte("prog.btn.anul"));
        supprimer=new Supprimer();
        supprimerDeLaBD=new ArrayList<>();
        supprimerDeLaListe=new ArrayList<>();
        
    }
    private void annuler(){
            supprimer.cancel(true);
            btnAnnuler.setEnabled(false);
            
            
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressBar = new javax.swing.JProgressBar();
        btnAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Suppression des donnes de Stagiaires");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        progressBar.setStringPainted(true);
        getContentPane().add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 30));

        btnAnnuler.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnnuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        // TODO add your handling code here:
        annuler();
    }//GEN-LAST:event_btnAnnulerActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
    public void demarreProgression(){
        progressBar.setVisible(true);
        supprimer.execute();
    }
    private class Supprimer extends SwingWorker<Void, Integer>{
         Object[] stagiaireSelectionne;

        Supprimer(){
            this.stagiaireSelectionne=parent.getListeStagiaire().getSelectedValues();
            progressBar.setMinimum(0);
            progressBar.setMaximum(stagiaireSelectionne.length);
            progressBar.setValue(0);
            progressBar.setVisible(true);
        }
        @Override
        protected Void doInBackground() throws Exception {
                    int n=0;
                    for(Object o:stagiaireSelectionne){
                        if(isCancelled()){
                            btnAnnuler.setText(I18n.texte("prog.anul"));
                            setTitle(I18n.texte("prog.rest"));
                            break;
                        }
                        Stagiaire stagiaire=(Stagiaire)o;
                        model.supprimerStagiaire(stagiaire.getMatricule());
                        supprimerDeLaBD.add(stagiaire);
                        publish(++n);
                        try{
                            Thread.sleep(100);
                        }catch(InterruptedException e){
                            return null;
                        }
                    }
            
            return null;
        }

        @Override
        protected void process(List<Integer> chunks) {
            int valeur=chunks.get(chunks.size()-1);
            progressBar.setValue(valeur);
        }

        @Override
        protected void done() {
            progressBar.setValue(parent.getListeStagiaire().getSelectedValues().length);
            if(isCancelled()){
                btnAnnuler.setText(I18n.texte("prog.anul"));
                setTitle(I18n.texte("prog.rest"));
                for(Stagiaire stagiaire:supprimerDeLaBD){
                    model.ajouterStagiaire(stagiaire);
                }
                for(Stagiaire stagiaire:supprimerDeLaListe){
                    liste.addElement(stagiaire);
                }
            }else{
                if(stagiaireSelectionne.length==liste.size())liste.clear();
                else{
                    for(Object o:stagiaireSelectionne){
                        liste.removeElement(o);
                        supprimerDeLaListe.add((Stagiaire)o);
                    }
                }
            }
            progressBar.setVisible(false);
            parent.getBtnVider().doClick();
            dispose();
        }
        
        
    }
}
